version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
  - dependency-name: "@reactivex/rxjs"
    versions:
    - 6.6.3
    - 6.6.6
  - dependency-name: validator
    versions:
    - 13.5.2
  - dependency-name: moment-timezone
    versions:
    - 0.5.32
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: node-cron
    versions:
    - 2.0.3
