version : '3'

services:
  leader:
    image: hurricane-scheduler:1.0
    environment: 
      NODE_ENV: dev
      PORT: 3000
      MONITORING_PORT: 9000
      SEED_NODES: leader:3000,follower-1:3001,follower-2:3002
      LEADER_MODE: 1
      LOG_LEVEL_ENGINE: debug
      LOG_FILE_ENGINE: engine.log
      JOB_PORT: 3030
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_USER: postmaster@sandbox9642d0fe56424868872cc623966c9fbd.mailgun.org
      SMTP_PWD: 4af411902f499da4674ebe210d3f6861-2b778fc3-7a6b70d3
      EMAIL_ALERTING_ENABLED: "false"
      EMAIL_LIST: alessandroardizio94@gmail.com
    hostname: leader
    ports: 
      - 3000:3000
      - 9000:9000
      - 3030:3030
  follower-1:
    image: hurricane-scheduler:1.0
    environment: 
      NODE_ENV: dev
      PORT: 3001
      MONITORING_PORT: 9001
      SEED_NODES: leader:3000,follower-1:3001,follower-2:3002
      LOG_LEVEL_ENGINE: debug
      LOG_FILE_ENGINE: engine.log
      JOB_PORT: 3031
      TIME_TO_RECONNECT: 5000
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_USER: postmaster@sandbox9642d0fe56424868872cc623966c9fbd.mailgun.org
      SMTP_PWD: 4af411902f499da4674ebe210d3f6861-2b778fc3-7a6b70d3
      EMAIL_ALERTING_ENABLED: "false"
      EMAIL_LIST: alessandroardizio94@gmail.com
    hostname: follower-1
    ports:
      - 3001:3001
      - 9001:9001
      - 3031:3030
    depends_on:
      - leader
  follower-2:
    image: hurricane-scheduler:1.0
    environment: 
      NODE_ENV: dev
      PORT: 3002
      MONITORING_PORT: 9002
      SEED_NODES: leader:3000,follower-1:3001,follower-2:3002
      LOG_LEVEL_ENGINE: debug
      LOG_FILE_ENGINE: engine.log
      JOB_PORT: 3032
      TIME_TO_RECONNECT: 5000
      SMTP_HOST: smtp.mailgun.org
      SMTP_PORT: 587
      SMTP_USER: postmaster@sandbox9642d0fe56424868872cc623966c9fbd.mailgun.org
      SMTP_PWD: 4af411902f499da4674ebe210d3f6861-2b778fc3-7a6b70d3
      EMAIL_ALERTING_ENABLED: "false"
      EMAIL_LIST: alessandroardizio94@gmail.com
    hostname: follower-2
    ports:
      - 3002:3002
      - 9002:9002
      - 3032:3030
    depends_on:
      - leader